---
    name: CI
    
    on:
        pull_request:
            branches: master
    jobs:
        build-and-test:
            name: Build and test
            runs-on: ubuntu-latest
            container: elixir:1.10-alpine
            steps:
                - uses: actions/checkout@v2
                - name: Install build dependencies
                  run: |
                    apk add --update bash openssl git
                    mix local.hex --force && mix local.rebar --force
                - name: Install elixir dependencies
                  env:
                    GOOGLE_SECRET_JSON: fake_value
                  run: mix deps.get
                - name: Run CI Tests
                  env:
                    MIX_ENV: test
                  run: mix cxi